Refactorization
rodi0878/NNPTP23-1 pull request #10
Opened 2023-11-18 01:22 UTC by JakubJoukl

2023-11-19 08:20 UTC, rodi0878 requested changes
please review comments and provide update

2023-11-19 08:20 UTC, rodi0878 commented on NNPTPZ1/Mathematics/Complex.cs
> +        public double GetAbsoluteValue()
better to group similiar methods together - getabsvalue + getangleinradians; mathematical methods; ...

2023-11-19 08:20 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            float newtonIteration = 0;
why float?

2023-11-19 08:20 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            chosenColor = Color.FromArgb(chosenColor.R, chosenColor.G, chosenColor.B);
this line does nothing

2023-11-25 13:46 UTC, JakubJoukl commented
Pushed the requested changes, see commit message for more details

2023-11-26 08:28 UTC, closed without merging

2023-11-26 08:28 UTC, rodi0878 commented
ok accepted