Refactoring - st72710 (Jan Stehno)
rodi0878/NNPTP23-1 pull request #11
Opened 2023-11-18 13:16 UTC by janstehno

- created class for polynomial
  - changed `Poly` to `Polynomial`
  - renamed attributes, methods, and variables
- created class for complex number
  - changed `Cplx` to `ComplexNumber`
  - renamed attributes, methods, and variables
- created class for fractal generation
  - created `Fractal`
  - extracted and renamed readonly attributes
  - extracted and renamed other used attributes
  - split `Main` to smaller methods
- changed tests accordingly
- removed unused and/or commented code
- program should be executable

2023-11-19 08:24 UTC, rodi0878 requested changes
please see attached comments and provide update. current version of code needs some additional tweaks

2023-11-19 08:24 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAbsolute()
wrong name, absolute value is technical term in complex numbers and should be preserved without any abbreviations or shortenings

2023-11-19 08:24 UTC, rodi0878 commented on NNPTPZ1/Fractal.cs
> +        internal readonly int NUMBER_OF_ITERATIONS = 30;
there is too much fields and in many cases you prefer this mess over direct return values from methods, this mades it really bad for comprehension of whats going on here...

2023-11-19 08:24 UTC, rodi0878 commented on NNPTPZ1/Fractal.cs
> +            complexNumber = new ComplexNumber()
this should be return value

2023-11-19 08:24 UTC, rodi0878 commented on NNPTPZ1/Fractal.cs
> +            iterations = 0;
this should be return value

2023-11-19 08:24 UTC, rodi0878 commented on NNPTPZ1/Fractal.cs
> +                position = roots.Count;
this should be return value

2023-11-19 09:28 UTC, janstehno commented
- requested changes made

Just to understand this, it is better to use parameters rather than global variables?

I can understand it for `position`, `iterations` and `currentComplexNumber`. But for me it does not make sense to do it the same way for `polynomial`, `derivatedPolynomial`, or `bitmap` for example. It is possible, sure, but I would have to pass them as parameters too many times in my opinion.

2023-11-23 11:35 UTC, rodi0878 commented
generally you should not try to hide any input/output from functions. Parameters should be preferred instead of fields/properties for passing of directly related data.

ok accepted

2023-11-23 11:35 UTC, closed without merging